apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ include "authorize-gateway-lab-web.fullname" . }}
  labels:
    {{- include "authorize-gateway-lab-web.labels" . | nindent 4 }}

spec:
  replicas: {{ .Values.replicaCount }}

  revisionHistoryLimit: 3

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1

  selector:
    matchLabels:
      {{- include "authorize-gateway-lab-web.selectorLabels" . | nindent 6 }}

  template:
    metadata:
      labels:
        {{- include "authorize-gateway-lab-web.selectorLabels" . | nindent 8 }}

    spec:
      containers:
        - name: authorize-gateway-lab-web

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - name: http
              containerPort: {{ .Values.container.port }}
              protocol: TCP

          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: {{ .Values.environment.aspnetcoreEnvironment | quote }}

            - name: ASPNETCORE_URLS
              value: {{ .Values.environment.aspnetcoreUrls | quote }}

          readinessProbe:
            httpGet:
              path: {{ .Values.probes.readiness.path }}
              port: http

            initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.readiness.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.readiness.timeoutSeconds }}
            failureThreshold: {{ .Values.probes.readiness.failureThreshold }}

          livenessProbe:
            httpGet:
              path: {{ .Values.probes.liveness.path }}
              port: http

            initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.liveness.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.liveness.timeoutSeconds }}
            failureThreshold: {{ .Values.probes.liveness.failureThreshold }}

          resources:
            {{- toYaml .Values.resources | nindent 12 }}